DECLARE
    v_existe NUMBER := 0;
BEGIN
    -- DATA_HORA_FINALIZACAO
    SELECT COUNT(*)
      INTO v_existe
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ALOCACAO_MOTO'
       AND COLUMN_NAME = 'DATA_HORA_FINALIZACAO';

    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ALOCACAO_MOTO ADD (DATA_HORA_FINALIZACAO TIMESTAMP)';
    END IF;

    -- STATUS
    SELECT COUNT(*)
      INTO v_existe
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ALOCACAO_MOTO'
       AND COLUMN_NAME = 'STATUS';

    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ALOCACAO_MOTO ADD (STATUS VARCHAR2(20) DEFAULT ''ATIVA'' NOT NULL)';
    END IF;

    -- MOTIVO_FINALIZACAO
    SELECT COUNT(*)
      INTO v_existe
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ALOCACAO_MOTO'
       AND COLUMN_NAME = 'MOTIVO_FINALIZACAO';

    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ALOCACAO_MOTO ADD (MOTIVO_FINALIZACAO VARCHAR2(500))';
    END IF;

    -- USUARIO_FINALIZACAO_ID
    SELECT COUNT(*)
      INTO v_existe
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ALOCACAO_MOTO'
       AND COLUMN_NAME = 'USUARIO_FINALIZACAO_ID';

    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ALOCACAO_MOTO ADD (USUARIO_FINALIZACAO_ID NUMBER(19))';
    END IF;

    -- Comentários (idempotentes)
    EXECUTE IMMEDIATE '
        COMMENT ON COLUMN ALOCACAO_MOTO.STATUS IS ''Status da alocação: ATIVA, REALOCADA, FINALIZADA, CANCELADA''
    ';

    EXECUTE IMMEDIATE '
        COMMENT ON COLUMN ALOCACAO_MOTO.DATA_HORA_FINALIZACAO IS ''Data e hora quando a alocação foi finalizada''
    ';

    EXECUTE IMMEDIATE '
        COMMENT ON COLUMN ALOCACAO_MOTO.MOTIVO_FINALIZACAO IS ''Motivo da finalização da alocação''
    ';

    EXECUTE IMMEDIATE '
        COMMENT ON COLUMN ALOCACAO_MOTO.USUARIO_FINALIZACAO_ID IS ''Usuário responsável pela finalização da alocação''
    ';

    -- Constraint da chave estrangeira
    SELECT COUNT(*)
      INTO v_existe
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'ALOCACAO_MOTO'
       AND CONSTRAINT_NAME = 'FK_ALOCACAO_MOTO_USUARIO_FINALIZACAO';

    IF v_existe = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE ALOCACAO_MOTO
            ADD CONSTRAINT FK_ALOCACAO_MOTO_USUARIO_FINALIZACAO
            FOREIGN KEY (USUARIO_FINALIZACAO_ID) REFERENCES USUARIO(ID)
        ';
    END IF;

    -- Índices
    FOR idx IN (
        SELECT 'IDX_ALOCACAO_MOTO_STATUS' AS nome, 'STATUS' AS coluna FROM dual UNION ALL
        SELECT 'IDX_ALOCACAO_MOTO_DATA_ALOCACAO', 'DATA_HORA_ALOCACAO' FROM dual UNION ALL
        SELECT 'IDX_ALOCACAO_MOTO_DATA_FINALIZACAO', 'DATA_HORA_FINALIZACAO' FROM dual UNION ALL
        SELECT 'IDX_ALOCACAO_MOTO_MOTO_STATUS', 'MOTO_ID, STATUS' FROM dual
    ) LOOP
        SELECT COUNT(*)
          INTO v_existe
          FROM USER_INDEXES
         WHERE INDEX_NAME = idx.nome;

        IF v_existe = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || idx.nome || ' ON ALOCACAO_MOTO(' || idx.coluna || ')';
        END IF;
    END LOOP;

    -- Atualiza valores nulos de STATUS
    EXECUTE IMMEDIATE '
        UPDATE ALOCACAO_MOTO
        SET STATUS = ''ATIVA''
        WHERE STATUS IS NULL
    ';

    COMMIT;
END;
/

SELECT 'Coluna USUARIO_FINALIZACAO_ID garantida na tabela ALOCACAO_MOTO.' AS STATUS FROM DUAL;

